/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BanDocBLL;
import BLL.TaiLieuBLL;
import BLL.TaiLieuMuonBLL;
import BLL.ThuThuBLL;
import Class.BanDoc;
import Class.TaiLieu;
import Class.TaiLieuMuon;
import Class.ThuThu;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author langt
 */
public class FrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    BanDocBLL banDocBLL = new BanDocBLL();
    TaiLieuBLL taiLieuBLL = new TaiLieuBLL();
    ThuThuBLL thuThuBLL = new ThuThuBLL();
    TaiLieuMuonBLL taiLieuMuonBLL = new TaiLieuMuonBLL();
    DefaultTableModel banDocModel;
    DefaultTableModel taiLieuModel;
    DefaultTableModel thuThuModel;
    DefaultTableModel taiLieuMuonModel;
    BanDoc banDoc = new BanDoc();
    ThuThu thuThu = new ThuThu();
    TaiLieu taiLieu = new TaiLieu();
    TaiLieuMuon taiLieuMuon = new TaiLieuMuon();
    int rowBanDoc = -1, rowThuThu = -1, rowTaiLieu = -1, rowTaiLieuMuon = -1;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

    public FrameAdmin() {
        initComponents();
        setLocationRelativeTo(this);
        banDocModel = (DefaultTableModel) tblBanDoc.getModel();
        taiLieuModel = (DefaultTableModel) tblTaiLieu.getModel();
        thuThuModel = (DefaultTableModel) tblThuThu.getModel();
        taiLieuMuonModel = (DefaultTableModel) tblTaiLieuMuon.getModel();
    }

    private void layThongTinBanDoc() {
        banDoc.setMaBanDoc(txtMaBanDoc.getText().trim());
        banDoc.setDiaChi(txtDiaChiBanDoc.getText().trim());
        banDoc.setLop(txtLop.getText().trim());
        banDoc.setNgaySinh(dcNgaySinhBanDoc.getDate());
        banDoc.setTenBanDoc(txtTenBanDoc.getText().trim());
    }

    private void layThongTinThuThu() {
        thuThu.setMaThuThu(txtMaThuThu.getText().trim());
        thuThu.setTenThuThu(txtTenThuThu.getText().trim());
        thuThu.setDiaChi(txtDiaChiThuThu.getText().trim());
        thuThu.setSoDT(txtSoDTThuThu.getText().trim());
        thuThu.setNgaySinh(dcNgaySinhThuThu.getDate());
    }

    private void layThongTinTaiLieu() {
        taiLieu.setMaTaiLieu(txtMaTaiLieu.getText().trim());
        taiLieu.setTenTaiLieu(txtTenTaiLieu.getText().trim());
        try {
            String soLuong = txtSoLuongTaiLieu.getText().trim();
            taiLieu.setSoLuong(soLuong.equals("") ? 0 : Integer.parseInt(soLuong));
        } catch (NumberFormatException e) {
            taiLieu.setSoLuong(0);
        }
        taiLieu.setNhaXuatBan(txtNhaXuatBan.getText().trim());
        try {
            String gia = txtGia.getText().trim();
            taiLieu.setGia(gia.equals("") ? 0 : Float.parseFloat(gia));
        } catch (NumberFormatException e) {
            taiLieu.setGia(0);
        }
    }

    private void layThongTinTaiLieuMuon() {
        taiLieuMuon.setMaTaiLieu(txtMaTaiLieuMuon.getText().trim());
        taiLieuMuon.setMaMuon(txtMaMuon.getText().trim());
        taiLieuMuon.setMaBanDoc(txtMaBanDocMuon.getText().trim());
        taiLieuMuon.setMaThuThu(txtMaThuThuChoMuon.getText().trim());
        try {
            String soLuong = txtSoLuongTaiLieu.getText().trim();
            taiLieuMuon.setSoLuong(soLuong.equals("") ? 0 : Integer.parseInt(soLuong));
        } catch (NumberFormatException e) {
            taiLieuMuon.setSoLuong(0);
        }
        taiLieuMuon.setNgayMuon(dcNgayMuon.getDate());
        taiLieuMuon.setNgayTra(dcNgayTra.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        PannelQLBanDoc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaBanDoc = new javax.swing.JTextField();
        txtTenBanDoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChiBanDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLop = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanDoc = new javax.swing.JTable();
        btnXemTatCaBanDoc = new javax.swing.JButton();
        btnThemBanDoc = new javax.swing.JButton();
        btnSuaBanDoc = new javax.swing.JButton();
        btnXoaBanDoc = new javax.swing.JButton();
        btnDatLaiBanDoc = new javax.swing.JButton();
        btnDatLaiMatKhauBanDoc = new javax.swing.JButton();
        txtTimKiemBanDoc = new javax.swing.JTextField();
        btnTimKiemBanDoc = new javax.swing.JButton();
        dcNgaySinhBanDoc = new com.toedter.calendar.JDateChooser();
        PanelQLThuThu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnDatLaiThuThu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnDatLaiMatKhauThuThu = new javax.swing.JButton();
        txtSoDTThuThu = new javax.swing.JTextField();
        txtTimKiemThuThu = new javax.swing.JTextField();
        btnTimKiemThuThu = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtMaThuThu = new javax.swing.JTextField();
        txtTenThuThu = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThuThu = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnXemTatCaThuThu = new javax.swing.JButton();
        btnThemThuThu = new javax.swing.JButton();
        btnSuaThuThu = new javax.swing.JButton();
        txtDiaChiThuThu = new javax.swing.JTextField();
        btnXoaThuThu = new javax.swing.JButton();
        dcNgaySinhThuThu = new com.toedter.calendar.JDateChooser();
        PanelQLTaiLieuMuon = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnDatLaiTaiLieuMuon = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtTimKiemTaiLieuMuon = new javax.swing.JTextField();
        btnTimKiemTaiLieuMuon = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtMaBanDocMuon = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTaiLieuMuon = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnXemTatCaTaiLieuMuon = new javax.swing.JButton();
        btnThemTaiLieuMuon = new javax.swing.JButton();
        btnSuaTaiLieuMuon = new javax.swing.JButton();
        btnXoaTaiLieuMuon = new javax.swing.JButton();
        txtMaTaiLieuMuon = new javax.swing.JTextField();
        txtMaThuThuChoMuon = new javax.swing.JTextField();
        txtSoLuongMuon = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        dcNgayMuon = new com.toedter.calendar.JDateChooser();
        dcNgayTra = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        txtMaMuon = new javax.swing.JTextField();
        PanelQLTaiLieu = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnDatLaiTaiLieu = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtTimKiemTaiLieu = new javax.swing.JTextField();
        btnTimKiemTaiLieu = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtMaTaiLieu = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTaiLieu = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnXemTatCaTaiLieu = new javax.swing.JButton();
        btnThemTaiLieu = new javax.swing.JButton();
        btnSuaTaiLieu = new javax.swing.JButton();
        btnXoaTaiLieu = new javax.swing.JButton();
        txtTenTaiLieu = new javax.swing.JTextField();
        txtSoLuongTaiLieu = new javax.swing.JTextField();
        txtNhaXuatBan = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quản lý bạn đọc");

        jLabel7.setText("Mã bạn đọc");

        jLabel8.setText("Tên bạn đọc");

        jLabel9.setText("Ngày sinh");

        jLabel10.setText("Địa chỉ");

        jLabel11.setText("Lớp");

        tblBanDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bạn đọc", "Tên bạn đọc", "Ngày sinh", "Địa chỉ", "Lớp"
            }
        ));
        tblBanDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanDocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBanDoc);

        btnXemTatCaBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaBanDoc.setText("Xem tất cả");
        btnXemTatCaBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTatCaBanDocActionPerformed(evt);
            }
        });

        btnThemBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemBanDoc.setText("Thêm");
        btnThemBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanDocActionPerformed(evt);
            }
        });

        btnSuaBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaBanDoc.setText("Sửa");
        btnSuaBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaBanDocActionPerformed(evt);
            }
        });

        btnXoaBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaBanDoc.setText("Xóa");
        btnXoaBanDoc.setName("Xóa"); // NOI18N
        btnXoaBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBanDocActionPerformed(evt);
            }
        });

        btnDatLaiBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiBanDoc.setText("Đặt lại");
        btnDatLaiBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiBanDocActionPerformed(evt);
            }
        });

        btnDatLaiMatKhauBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-reset-48.png"))); // NOI18N
        btnDatLaiMatKhauBanDoc.setText("Đặt lại mật khẩu");
        btnDatLaiMatKhauBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiMatKhauBanDocActionPerformed(evt);
            }
        });

        txtTimKiemBanDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemBanDoc.setText("Tìm kiếm");
        btnTimKiemBanDoc.setNextFocusableComponent(txtMaBanDoc);
        btnTimKiemBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemBanDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelQLBanDocLayout = new javax.swing.GroupLayout(PannelQLBanDoc);
        PannelQLBanDoc.setLayout(PannelQLBanDocLayout);
        PannelQLBanDocLayout.setHorizontalGroup(
            PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addComponent(txtTimKiemBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiemBanDoc))
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelQLBanDocLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)))
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLop, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtMaBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtTenBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtDiaChiBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(dcNgaySinhBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXemTatCaBanDoc)
                            .addComponent(btnDatLaiBanDoc)
                            .addComponent(btnDatLaiMatKhauBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaBanDoc)
                            .addComponent(btnSuaBanDoc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
        );

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatLaiBanDoc, btnDatLaiMatKhauBanDoc, btnSuaBanDoc, btnThemBanDoc, btnXemTatCaBanDoc, btnXoaBanDoc});

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiaChiBanDoc, txtLop, txtMaBanDoc, txtTenBanDoc});

        PannelQLBanDocLayout.setVerticalGroup(
            PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemBanDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel9))
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addComponent(txtMaBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(dcNgaySinhBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiaChiBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaBanDoc)
                            .addComponent(btnThemBanDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiBanDoc)
                            .addComponent(btnXoaBanDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiMatKhauBanDoc)
                            .addComponent(btnSuaBanDoc)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDatLaiBanDoc, btnDatLaiMatKhauBanDoc, btnSuaBanDoc, btnThemBanDoc, btnXemTatCaBanDoc, btnXoaBanDoc});

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtLop, txtMaBanDoc, txtTenBanDoc});

        btnXoaBanDoc.getAccessibleContext().setAccessibleName("btnXoa");

        jTabbedPane2.addTab("Quản lý bạn đọc", PannelQLBanDoc);

        jLabel16.setText("Địa chỉ");

        btnDatLaiThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiThuThu.setText("Đặt lại");
        btnDatLaiThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiThuThuActionPerformed(evt);
            }
        });

        jLabel17.setText("Số điện thoại");

        btnDatLaiMatKhauThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-reset-48.png"))); // NOI18N
        btnDatLaiMatKhauThuThu.setText("Đặt lại mật khẩu");
        btnDatLaiMatKhauThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiMatKhauThuThuActionPerformed(evt);
            }
        });

        txtTimKiemThuThu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemThuThu.setText("Tìm kiếm");
        btnTimKiemThuThu.setNextFocusableComponent(txtMaThuThu);
        btnTimKiemThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemThuThuActionPerformed(evt);
            }
        });

        jLabel18.setText("Mã thủ thư");

        tblThuThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thủ thư", "Tên thủ thư", "Ngày sinh", "Địa chỉ", "Số điện thoại"
            }
        ));
        tblThuThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuThuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThuThu);

        jLabel19.setText("Tên thủ thư");

        jLabel20.setText("Ngày sinh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Quản lý thủ thư");

        btnXemTatCaThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaThuThu.setText("Xem tất cả");
        btnXemTatCaThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTatCaThuThuActionPerformed(evt);
            }
        });

        btnThemThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemThuThu.setText("Thêm");
        btnThemThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuThuActionPerformed(evt);
            }
        });

        btnSuaThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaThuThu.setText("Sửa");
        btnSuaThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThuThuActionPerformed(evt);
            }
        });

        btnXoaThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaThuThu.setText("Xóa");
        btnXoaThuThu.setName("Xóa"); // NOI18N
        btnXoaThuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelQLThuThuLayout = new javax.swing.GroupLayout(PanelQLThuThu);
        PanelQLThuThu.setLayout(PanelQLThuThuLayout);
        PanelQLThuThuLayout.setHorizontalGroup(
            PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addComponent(txtTimKiemThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiemThuThu))
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)))
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoDTThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenThuThu)
                                    .addComponent(dcNgaySinhThuThu, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtDiaChiThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXemTatCaThuThu)
                            .addComponent(btnDatLaiThuThu)
                            .addComponent(btnDatLaiMatKhauThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaThuThu)
                            .addComponent(btnSuaThuThu))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );

        PanelQLThuThuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcNgaySinhThuThu, txtDiaChiThuThu, txtMaThuThu, txtSoDTThuThu, txtTenThuThu});

        PanelQLThuThuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatLaiMatKhauThuThu, btnDatLaiThuThu, btnSuaThuThu, btnThemThuThu, btnXemTatCaThuThu, btnXoaThuThu});

        PanelQLThuThuLayout.setVerticalGroup(
            PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemThuThu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addComponent(txtMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcNgaySinhThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChiThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDTThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaThuThu)
                            .addComponent(btnThemThuThu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiThuThu)
                            .addComponent(btnXoaThuThu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiMatKhauThuThu)
                            .addComponent(btnSuaThuThu)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelQLThuThuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDatLaiMatKhauThuThu, btnDatLaiThuThu, btnSuaThuThu, btnThemThuThu, btnXemTatCaThuThu, btnXoaThuThu});

        jTabbedPane2.addTab("Quản lý thủ thư", PanelQLThuThu);

        jLabel27.setText("Số lượng");

        btnDatLaiTaiLieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiTaiLieuMuon.setText("Đặt lại");
        btnDatLaiTaiLieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiTaiLieuMuonActionPerformed(evt);
            }
        });

        jLabel28.setText("Ngày mượn");

        txtTimKiemTaiLieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemTaiLieuMuon.setText("Tìm kiếm");
        btnTimKiemTaiLieuMuon.setNextFocusableComponent(txtMaBanDocMuon);
        btnTimKiemTaiLieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTaiLieuMuonActionPerformed(evt);
            }
        });

        jLabel29.setText("Mã bạn đọc");

        tblTaiLieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mượn", "Mã bạn đọc", "Mã tài liệu", "Mã thủ thư", "Số lượng", "Ngày mượn", "Ngày trả"
            }
        ));
        tblTaiLieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiLieuMuonMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTaiLieuMuon);

        jLabel30.setText("Mã tài liệu");

        jLabel31.setText("Mã thủ thư");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Quản lý Tài liệu mượn");

        btnXemTatCaTaiLieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaTaiLieuMuon.setText("Xem tất cả");
        btnXemTatCaTaiLieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTatCaTaiLieuMuonActionPerformed(evt);
            }
        });

        btnThemTaiLieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemTaiLieuMuon.setText("Thêm");
        btnThemTaiLieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiLieuMuonActionPerformed(evt);
            }
        });

        btnSuaTaiLieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaTaiLieuMuon.setText("Sửa");
        btnSuaTaiLieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTaiLieuMuonActionPerformed(evt);
            }
        });

        btnXoaTaiLieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaTaiLieuMuon.setText("Xóa");
        btnXoaTaiLieuMuon.setName("Xóa"); // NOI18N
        btnXoaTaiLieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiLieuMuonActionPerformed(evt);
            }
        });

        jLabel33.setText("Ngày trả");

        jLabel34.setText("Mã mượn");

        javax.swing.GroupLayout PanelQLTaiLieuMuonLayout = new javax.swing.GroupLayout(PanelQLTaiLieuMuon);
        PanelQLTaiLieuMuon.setLayout(PanelQLTaiLieuMuonLayout);
        PanelQLTaiLieuMuonLayout.setHorizontalGroup(
            PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel32)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                            .addComponent(txtTimKiemTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTimKiemTaiLieuMuon))
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXemTatCaTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDatLaiTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoaTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSuaTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel33))
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaBanDocMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaThuThuChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaMuon)))))
                    .addComponent(jLabel34))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelQLTaiLieuMuonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcNgayMuon, dcNgayTra, txtMaBanDocMuon, txtMaTaiLieuMuon, txtMaThuThuChoMuon, txtSoLuongMuon});

        PanelQLTaiLieuMuonLayout.setVerticalGroup(
            PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemTaiLieuMuon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                                .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtMaBanDocMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtMaThuThuChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtSoLuongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27)))
                                    .addGroup(PanelQLTaiLieuMuonLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel30)))
                                .addGap(18, 18, 18)
                                .addComponent(dcNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaTaiLieuMuon)
                            .addComponent(btnThemTaiLieuMuon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLTaiLieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiTaiLieuMuon)
                            .addComponent(btnXoaTaiLieuMuon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuaTaiLieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        PanelQLTaiLieuMuonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcNgayMuon, dcNgayTra, txtMaBanDocMuon, txtMaTaiLieuMuon, txtMaThuThuChoMuon, txtSoLuongMuon});

        jTabbedPane2.addTab("Quản lý tài liệu mượn", PanelQLTaiLieuMuon);

        jLabel21.setText("Nhà xuất bản");

        btnDatLaiTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiTaiLieu.setText("Đặt lại");
        btnDatLaiTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiTaiLieuActionPerformed(evt);
            }
        });

        jLabel22.setText("Giá");

        txtTimKiemTaiLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemTaiLieu.setText("Tìm kiếm");
        btnTimKiemTaiLieu.setNextFocusableComponent(txtMaTaiLieu);
        btnTimKiemTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTaiLieuActionPerformed(evt);
            }
        });

        jLabel23.setText("Mã tài liệu");

        tblTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài liệu", "Tên tài liệu", "Số lượng", "Nhà xuất bản", "Giá"
            }
        ));
        tblTaiLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiLieuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTaiLieu);

        jLabel24.setText("Tên tài liệu");

        jLabel25.setText("Số lượng");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Quản lý Tài liệu");

        btnXemTatCaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaTaiLieu.setText("Xem tất cả");
        btnXemTatCaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTatCaTaiLieuActionPerformed(evt);
            }
        });

        btnThemTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemTaiLieu.setText("Thêm");
        btnThemTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiLieuActionPerformed(evt);
            }
        });

        btnSuaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaTaiLieu.setText("Sửa");
        btnSuaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTaiLieuActionPerformed(evt);
            }
        });

        btnXoaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaTaiLieu.setText("Xóa");
        btnXoaTaiLieu.setName("Xóa"); // NOI18N
        btnXoaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelQLTaiLieuLayout = new javax.swing.GroupLayout(PanelQLTaiLieu);
        PanelQLTaiLieu.setLayout(PanelQLTaiLieuLayout);
        PanelQLTaiLieuLayout.setHorizontalGroup(
            PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel26)
                .addGap(0, 498, Short.MAX_VALUE))
            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                        .addComponent(txtTimKiemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiemTaiLieu))
                    .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                            .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel23)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24))
                            .addGap(18, 18, 18)
                            .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoLuongTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnSuaTaiLieu)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelQLTaiLieuLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                    .addComponent(btnDatLaiTaiLieu)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnXoaTaiLieu))
                                .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                    .addComponent(btnXemTatCaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnThemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
        );

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatLaiTaiLieu, btnSuaTaiLieu, btnThemTaiLieu, btnXemTatCaTaiLieu, btnXoaTaiLieu});

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtGia, txtMaTaiLieu, txtNhaXuatBan, txtSoLuongTaiLieu, txtTenTaiLieu});

        PanelQLTaiLieuLayout.setVerticalGroup(
            PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemTaiLieu))
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel24))
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoLuongTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaTaiLieu)
                            .addComponent(btnThemTaiLieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiTaiLieu)
                            .addComponent(btnXoaTaiLieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaTaiLieu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDatLaiTaiLieu, btnSuaTaiLieu, btnThemTaiLieu, btnXemTatCaTaiLieu, btnXoaTaiLieu});

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtGia, txtMaTaiLieu, txtNhaXuatBan, txtSoLuongTaiLieu, txtTenTaiLieu});

        jTabbedPane2.addTab("Quản lý tài liệu", PanelQLTaiLieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiLieuActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaTaiLieu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã tài liệu không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtTenTaiLieu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên tài liệu không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                layThongTinTaiLieu();
                if (taiLieuBLL.themTaiLieu(taiLieu)) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    btnXemTatCaTaiLieuActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Trùng mã tài liệu");
                    JOptionPane.showMessageDialog(null, "Thêm không thành công");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnThemTaiLieuActionPerformed

    private void btnXemTatCaBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTatCaBanDocActionPerformed
        // TODO add your handling code here:
        banDocModel.setRowCount(0);
        banDocModel = banDocBLL.xemTatCaBanDoc(tblBanDoc);
        if (banDocModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có bạn đọc nào");
        }
    }//GEN-LAST:event_btnXemTatCaBanDocActionPerformed

    private void btnThemBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanDocActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaBanDoc.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã bạn đọc không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtTenBanDoc.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên bạn đọc không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (dcNgaySinhBanDoc.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ngày sinh bạn đọc không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                layThongTinBanDoc();
                if (banDocBLL.themBanDoc(banDoc)) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    btnXemTatCaBanDocActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Trùng mã bạn đọc");
                    JOptionPane.showMessageDialog(null, "Thêm không thành công");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_btnThemBanDocActionPerformed

    private void btnDatLaiBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiBanDocActionPerformed
        // TODO add your handling code here:
        txtMaBanDoc.setText("");
        txtTenBanDoc.setText("");
        txtDiaChiBanDoc.setText("");
        txtLop.setText("");
        dcNgaySinhBanDoc.setDate(null);
    }//GEN-LAST:event_btnDatLaiBanDocActionPerformed

    private void btnXoaBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBanDocActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc xóa bạn đọc: " + txtMaBanDoc.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            if (banDocBLL.xoaBanDoc(tblBanDoc.getValueAt(rowBanDoc, 0).toString())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                btnXemTatCaBanDocActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaBanDocActionPerformed

    private void btnDatLaiMatKhauBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiMatKhauBanDocActionPerformed
        // TODO add your handling code here:
        layThongTinBanDoc();
        try {
            int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn đặt lại?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                if (banDocBLL.datLaiMatKhau(banDoc)) {
                    JOptionPane.showMessageDialog(null, "Đặt lại thành công");
                    btnXemTatCaBanDocActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Đặt lại không thành công");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnDatLaiMatKhauBanDocActionPerformed

    private void tblBanDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanDocMouseClicked
        // TODO add your handling code here:
        rowBanDoc = tblBanDoc.getSelectedRow();
        txtMaBanDoc.setText(banDocModel.getValueAt(rowBanDoc, 0).toString());
        txtTenBanDoc.setText(banDocModel.getValueAt(rowBanDoc, 1).toString());
        txtDiaChiBanDoc.setText(banDocModel.getValueAt(rowBanDoc, 3).toString());
        txtLop.setText(banDocModel.getValueAt(rowBanDoc, 4).toString());
        try {
            dcNgaySinhBanDoc.setDate(format.parse(banDocModel.getValueAt(rowBanDoc, 2).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(FrameAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblBanDocMouseClicked

    private void btnSuaBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaBanDocActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaBanDoc.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã bạn đọc không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtTenBanDoc.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên bạn đọc không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (dcNgaySinhBanDoc.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ngày sinh bạn đọc không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                int i = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    layThongTinBanDoc();
                    if (banDocBLL.suaBanDoc(banDoc)) {
                        JOptionPane.showMessageDialog(null, "Sửa thành công");
                        btnXemTatCaBanDocActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(null, "Sửa không thành công");
                    }
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnSuaBanDocActionPerformed

    private void btnTimKiemBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemBanDocActionPerformed
        // TODO add your handling code here:
        banDocModel.setRowCount(0);
        banDocModel = banDocBLL.timKiemBanDoc(tblBanDoc, txtTimKiemBanDoc.getText().trim());
        if (banDocModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có tài liệu mượn nào");
        }
    }//GEN-LAST:event_btnTimKiemBanDocActionPerformed

    private void btnXemTatCaThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTatCaThuThuActionPerformed
        // TODO add your handling code here:
        thuThuModel.setRowCount(0);
        thuThuModel = thuThuBLL.xemTatCaThuThu(tblThuThu);
        if (thuThuModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có thủ thư nào");
        }
    }//GEN-LAST:event_btnXemTatCaThuThuActionPerformed

    private void btnThemThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuThuActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaThuThu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã thủ thư không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtTenThuThu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên thủ thư không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (dcNgaySinhThuThu.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ngày sinh thủ thư không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                layThongTinThuThu();
                if (thuThuBLL.themThuThu(thuThu)) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    btnXemTatCaThuThuActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Trùng mã thủ thư");
                    JOptionPane.showMessageDialog(null, "Thêm không thành công");
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnThemThuThuActionPerformed

    private void btnDatLaiThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiThuThuActionPerformed
        // TODO add your handling code here:
        txtMaThuThu.setText("");
        txtTenThuThu.setText("");
        txtDiaChiThuThu.setText("");
        txtSoDTThuThu.setText("");
        dcNgaySinhThuThu.setDate(null);
    }//GEN-LAST:event_btnDatLaiThuThuActionPerformed

    private void btnSuaThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThuThuActionPerformed
        // TODO add your handling code here:

        try {
            if (txtMaThuThu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã thủ thư không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtTenThuThu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên thủ thư không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (dcNgaySinhThuThu.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ngày sinh thủ thư không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                int i = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    layThongTinThuThu();
                    if (thuThuBLL.suaThuThu(thuThu)) {
                        JOptionPane.showMessageDialog(null, "Sửa thành công");
                        btnXemTatCaThuThuActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(null, "Sửa không thành công");
                    }
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnSuaThuThuActionPerformed

    private void tblThuThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuThuMouseClicked
        // TODO add your handling code here:
        rowThuThu = tblThuThu.getSelectedRow();
        txtMaThuThu.setText(thuThuModel.getValueAt(rowThuThu, 0).toString());
        txtTenThuThu.setText(thuThuModel.getValueAt(rowThuThu, 1).toString());
        txtDiaChiThuThu.setText(thuThuModel.getValueAt(rowThuThu, 3).toString());
        txtSoDTThuThu.setText(thuThuModel.getValueAt(rowThuThu, 4).toString());
        try {
            dcNgaySinhThuThu.setDate(format.parse(thuThuModel.getValueAt(rowThuThu, 2).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(FrameAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblThuThuMouseClicked

    private void btnXoaThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuThuActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc xóa thủ thư: " + txtMaThuThu.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            if (thuThuBLL.xoaThuThu(txtMaThuThu.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                btnXemTatCaThuThuActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaThuThuActionPerformed

    private void btnDatLaiMatKhauThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiMatKhauThuThuActionPerformed
        // TODO add your handling code here:
        layThongTinThuThu();
        try {
            int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn đặt lại?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                if (thuThuBLL.datLaiMatKhau(thuThu)) {
                    JOptionPane.showMessageDialog(null, "Đặt lại thành công");
                    btnXemTatCaThuThuActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Đặt lại không thành công");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_btnDatLaiMatKhauThuThuActionPerformed

    private void btnTimKiemThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemThuThuActionPerformed
        // TODO add your handling code here:
        thuThuModel.setRowCount(0);
        thuThuModel = thuThuBLL.timKiemThuThu(tblThuThu, txtTimKiemThuThu.getText().trim());
        if (thuThuModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có thủ thư nào");
        }
    }//GEN-LAST:event_btnTimKiemThuThuActionPerformed

    private void btnXemTatCaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTatCaTaiLieuActionPerformed
        // TODO add your handling code here:
        taiLieuModel.setRowCount(0);
        taiLieuModel = taiLieuBLL.xemTatCaTaiLieu(tblTaiLieu);
        if (taiLieuModel.getRowCount() < 0) {
            JOptionPane.showMessageDialog(null, "Không có tài liệu nào");
        }

    }//GEN-LAST:event_btnXemTatCaTaiLieuActionPerformed

    private void btnDatLaiTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiTaiLieuActionPerformed
        // TODO add your handling code here:
        txtMaTaiLieu.setText("");
        txtTenTaiLieu.setText("");
        txtSoLuongTaiLieu.setText("");
        txtNhaXuatBan.setText("");
        txtGia.setText("");
    }//GEN-LAST:event_btnDatLaiTaiLieuActionPerformed

    private void btnXoaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiLieuActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc xóa tài liệu: " + txtMaTaiLieu.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            if (taiLieuBLL.xoaTaiLieu(txtMaTaiLieu.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                btnXemTatCaTaiLieuActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaTaiLieuActionPerformed

    private void btnSuaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTaiLieuActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaTaiLieu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã tài liệu không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtTenTaiLieu.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên tài liệu không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                int i = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    layThongTinTaiLieu();
                    if (taiLieuBLL.suaTaiLieu(taiLieu)) {
                        JOptionPane.showMessageDialog(null, "Sửa thành công");
                        btnXemTatCaTaiLieuActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(null, "Sửa không thành công");
                    }
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnSuaTaiLieuActionPerformed

    private void tblTaiLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiLieuMouseClicked
        // TODO add your handling code here:
        rowTaiLieu = tblTaiLieu.getSelectedRow();
        txtMaTaiLieu.setText(taiLieuModel.getValueAt(rowTaiLieu, 0).toString());
        txtTenTaiLieu.setText(taiLieuModel.getValueAt(rowTaiLieu, 1).toString());
        txtSoLuongTaiLieu.setText(taiLieuModel.getValueAt(rowTaiLieu, 2).toString());
        txtNhaXuatBan.setText(taiLieuModel.getValueAt(rowTaiLieu, 3).toString());
        txtGia.setText(taiLieuModel.getValueAt(rowTaiLieu, 4).toString());

    }//GEN-LAST:event_tblTaiLieuMouseClicked

    private void btnDatLaiTaiLieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiTaiLieuMuonActionPerformed
        // TODO add your handling code here:
        txtMaMuon.setText("");
        txtMaBanDocMuon.setText("");
        txtMaTaiLieuMuon.setText("");
        txtMaThuThuChoMuon.setText("");
        txtSoLuongMuon.setText("");
        dcNgayMuon.setDate(null);
        dcNgayTra.setDate(null);
    }//GEN-LAST:event_btnDatLaiTaiLieuMuonActionPerformed

    private void tblTaiLieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiLieuMuonMouseClicked
        // TODO add your handling code here:
        rowTaiLieuMuon = tblTaiLieuMuon.getSelectedRow();
        txtMaMuon.setText(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 0).toString());
        txtMaBanDocMuon.setText(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 1).toString());
        txtMaTaiLieuMuon.setText(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 2).toString());
        txtMaThuThuChoMuon.setText(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 3).toString());
        txtSoLuongMuon.setText(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 4).toString());
        try {
            dcNgayMuon.setDate(format.parse(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 5).toString()));
            dcNgayTra.setDate(format.parse(taiLieuMuonModel.getValueAt(rowTaiLieuMuon, 6).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(FrameAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblTaiLieuMuonMouseClicked

    private void btnXemTatCaTaiLieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTatCaTaiLieuMuonActionPerformed
        // TODO add your handling code here:
        taiLieuMuonModel.setRowCount(0);
        taiLieuMuonModel = taiLieuMuonBLL.xemTatCaTaiLieuMuon(tblTaiLieuMuon);
        if (taiLieuMuonModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có tài liệu mượn nào");
        }
    }//GEN-LAST:event_btnXemTatCaTaiLieuMuonActionPerformed

    private void btnThemTaiLieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiLieuMuonActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtMaBanDocMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã bạn đọc mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtMaTaiLieuMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã tài liệu mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtMaThuThuChoMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã thủ thư cho mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (dcNgayMuon.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ngày mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                layThongTinTaiLieuMuon();
                if (taiLieuMuonBLL.themTaiLieuMuon(taiLieuMuon)) {
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    btnXemTatCaTaiLieuMuonActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Trùng mã tài liệu mượn");
                    JOptionPane.showMessageDialog(null, "Thêm không thành công");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnThemTaiLieuMuonActionPerformed

    private void btnSuaTaiLieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTaiLieuMuonActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtMaBanDocMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã bạn đọc mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtMaTaiLieuMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã tài liệu mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (txtMaThuThuChoMuon.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Mã thủ thư cho mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else if (dcNgayMuon.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Ngày mượn không được trống", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                layThongTinTaiLieuMuon();
                if (taiLieuMuonBLL.suaTaiLieuMuon(taiLieuMuon)) {
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    btnXemTatCaTaiLieuMuonActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Sửa không thành công");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnSuaTaiLieuMuonActionPerformed

    private void btnXoaTaiLieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiLieuMuonActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Bạn có chắc xóa tài liệu mượn: " + txtMaMuon.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            if (taiLieuMuonBLL.xoaTaiLieuMuon(txtMaMuon.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                btnXemTatCaTaiLieuMuonActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa không thành công");
            }
        }
    }//GEN-LAST:event_btnXoaTaiLieuMuonActionPerformed

    private void btnTimKiemTaiLieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTaiLieuMuonActionPerformed
        // TODO add your handling code here:
        taiLieuMuonModel.setRowCount(0);
        taiLieuMuonModel = taiLieuMuonBLL.timKiemTaiLieuMuon(tblTaiLieuMuon, txtTimKiemTaiLieuMuon.getText().trim());
        if (taiLieuMuonModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có tài liệu mượn nào");
        }

    }//GEN-LAST:event_btnTimKiemTaiLieuMuonActionPerformed

    private void btnTimKiemTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTaiLieuActionPerformed
        // TODO add your handling code here:
        taiLieuModel.setRowCount(0);
        taiLieuModel=taiLieuBLL.timKiemTaiLieu(tblTaiLieu,txtTimKiemTaiLieu.getText().trim());
        if (taiLieuModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Không có tài liệu mượn nào");
        }
    }//GEN-LAST:event_btnTimKiemTaiLieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FrameAdmin().setVisible(true);
                }
            });
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrameAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelQLTaiLieu;
    private javax.swing.JPanel PanelQLTaiLieuMuon;
    private javax.swing.JPanel PanelQLThuThu;
    private javax.swing.JPanel PannelQLBanDoc;
    private javax.swing.JButton btnDatLaiBanDoc;
    private javax.swing.JButton btnDatLaiMatKhauBanDoc;
    private javax.swing.JButton btnDatLaiMatKhauThuThu;
    private javax.swing.JButton btnDatLaiTaiLieu;
    private javax.swing.JButton btnDatLaiTaiLieuMuon;
    private javax.swing.JButton btnDatLaiThuThu;
    private javax.swing.JButton btnSuaBanDoc;
    private javax.swing.JButton btnSuaTaiLieu;
    private javax.swing.JButton btnSuaTaiLieuMuon;
    private javax.swing.JButton btnSuaThuThu;
    private javax.swing.JButton btnThemBanDoc;
    private javax.swing.JButton btnThemTaiLieu;
    private javax.swing.JButton btnThemTaiLieuMuon;
    private javax.swing.JButton btnThemThuThu;
    private javax.swing.JButton btnTimKiemBanDoc;
    private javax.swing.JButton btnTimKiemTaiLieu;
    private javax.swing.JButton btnTimKiemTaiLieuMuon;
    private javax.swing.JButton btnTimKiemThuThu;
    private javax.swing.JButton btnXemTatCaBanDoc;
    private javax.swing.JButton btnXemTatCaTaiLieu;
    private javax.swing.JButton btnXemTatCaTaiLieuMuon;
    private javax.swing.JButton btnXemTatCaThuThu;
    private javax.swing.JButton btnXoaBanDoc;
    private javax.swing.JButton btnXoaTaiLieu;
    private javax.swing.JButton btnXoaTaiLieuMuon;
    private javax.swing.JButton btnXoaThuThu;
    private com.toedter.calendar.JDateChooser dcNgayMuon;
    private com.toedter.calendar.JDateChooser dcNgaySinhBanDoc;
    private com.toedter.calendar.JDateChooser dcNgaySinhThuThu;
    private com.toedter.calendar.JDateChooser dcNgayTra;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblBanDoc;
    private javax.swing.JTable tblTaiLieu;
    private javax.swing.JTable tblTaiLieuMuon;
    private javax.swing.JTable tblThuThu;
    private javax.swing.JTextField txtDiaChiBanDoc;
    private javax.swing.JTextField txtDiaChiThuThu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaBanDoc;
    private javax.swing.JTextField txtMaBanDocMuon;
    private javax.swing.JTextField txtMaMuon;
    private javax.swing.JTextField txtMaTaiLieu;
    private javax.swing.JTextField txtMaTaiLieuMuon;
    private javax.swing.JTextField txtMaThuThu;
    private javax.swing.JTextField txtMaThuThuChoMuon;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtSoDTThuThu;
    private javax.swing.JTextField txtSoLuongMuon;
    private javax.swing.JTextField txtSoLuongTaiLieu;
    private javax.swing.JTextField txtTenBanDoc;
    private javax.swing.JTextField txtTenTaiLieu;
    private javax.swing.JTextField txtTenThuThu;
    private javax.swing.JTextField txtTimKiemBanDoc;
    private javax.swing.JTextField txtTimKiemTaiLieu;
    private javax.swing.JTextField txtTimKiemTaiLieuMuon;
    private javax.swing.JTextField txtTimKiemThuThu;
    // End of variables declaration//GEN-END:variables
}
