/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author langt
 */
public class FrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    public FrameAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        PannelQLBanDoc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaBanDoc = new javax.swing.JTextField();
        txtTenBanDoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChiBanDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLop = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanDoc = new javax.swing.JTable();
        btnXemTatCaBanDoc = new javax.swing.JButton();
        btnThemBanDoc = new javax.swing.JButton();
        btnSuaBanDoc = new javax.swing.JButton();
        btnXoaBanDoc = new javax.swing.JButton();
        btnDatLaiBanDoc = new javax.swing.JButton();
        btnDatLaiMatKhauBanDoc = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiemBanDoc = new javax.swing.JButton();
        dcNgaySinhBanDoc = new com.toedter.calendar.JDateChooser();
        PanelQLTaiLieu = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnDatLaiTaiLieu = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtTimKiemTaiLieu = new javax.swing.JTextField();
        btnTimKiemTaiLieu = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtMaTieuLieu = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTaiLieu = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnXemTatCaTaiLieu = new javax.swing.JButton();
        btnThemTaiLieu = new javax.swing.JButton();
        btnSuaTaiLieu = new javax.swing.JButton();
        btnXoaTaiLieu = new javax.swing.JButton();
        txtTenTaiLieu = new javax.swing.JTextField();
        txtSoLuongTaiLieu = new javax.swing.JTextField();
        txtNhaSanXuat = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        PanelQLThuThu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnDatLaiThuThu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnDatLaiMatKhauThuThu = new javax.swing.JButton();
        txtSoDTThuThu = new javax.swing.JTextField();
        txtTimKiemThuThu = new javax.swing.JTextField();
        btnTimKiemThuThu = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtMaThuThu = new javax.swing.JTextField();
        txtTenThuThu = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThuThu = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnXemTatCaThuThu = new javax.swing.JButton();
        btnThemThuThu = new javax.swing.JButton();
        btnSuaThuThu = new javax.swing.JButton();
        txtDiaChiThuThu = new javax.swing.JTextField();
        btnXoaThuThu = new javax.swing.JButton();
        dcNgaySinhThuThu = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quản lý bạn đọc");

        jLabel7.setText("Mã bạn đọc");

        jLabel8.setText("Tên bạn đọc");

        jLabel9.setText("Ngày sinh");

        jLabel10.setText("Địa chỉ");

        jLabel11.setText("Lớp");

        tblBanDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bạn đọc", "Tên bạn đọc", "Ngày sinh", "Địa chỉ", "Lớp"
            }
        ));
        jScrollPane1.setViewportView(tblBanDoc);

        btnXemTatCaBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaBanDoc.setText("Xem tất cả");

        btnThemBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemBanDoc.setText("Thêm");

        btnSuaBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaBanDoc.setText("Sửa");

        btnXoaBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaBanDoc.setText("Xóa");
        btnXoaBanDoc.setName("Xóa"); // NOI18N

        btnDatLaiBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiBanDoc.setText("Đặt lại");

        btnDatLaiMatKhauBanDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-reset-48.png"))); // NOI18N
        btnDatLaiMatKhauBanDoc.setText("Đặt lại mật khẩu");

        txtTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemBanDoc.setText("Tìm kiếm");
        btnTimKiemBanDoc.setNextFocusableComponent(txtMaBanDoc);

        javax.swing.GroupLayout PannelQLBanDocLayout = new javax.swing.GroupLayout(PannelQLBanDoc);
        PannelQLBanDoc.setLayout(PannelQLBanDocLayout);
        PannelQLBanDocLayout.setHorizontalGroup(
            PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiemBanDoc))
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelQLBanDocLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)))
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLop, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtMaBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtTenBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtDiaChiBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(dcNgaySinhBanDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXemTatCaBanDoc)
                            .addComponent(btnDatLaiBanDoc)
                            .addComponent(btnDatLaiMatKhauBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaBanDoc)
                            .addComponent(btnSuaBanDoc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
        );

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatLaiBanDoc, btnDatLaiMatKhauBanDoc, btnSuaBanDoc, btnThemBanDoc, btnXemTatCaBanDoc, btnXoaBanDoc});

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiaChiBanDoc, txtLop, txtMaBanDoc, txtTenBanDoc});

        PannelQLBanDocLayout.setVerticalGroup(
            PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemBanDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel9))
                            .addGroup(PannelQLBanDocLayout.createSequentialGroup()
                                .addComponent(txtMaBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(dcNgaySinhBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiaChiBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaBanDoc)
                            .addComponent(btnThemBanDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiBanDoc)
                            .addComponent(btnXoaBanDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PannelQLBanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiMatKhauBanDoc)
                            .addComponent(btnSuaBanDoc)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDatLaiBanDoc, btnDatLaiMatKhauBanDoc, btnSuaBanDoc, btnThemBanDoc, btnXemTatCaBanDoc, btnXoaBanDoc});

        PannelQLBanDocLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtLop, txtMaBanDoc, txtTenBanDoc});

        btnXoaBanDoc.getAccessibleContext().setAccessibleName("btnXoa");

        jTabbedPane2.addTab("Quản lý bạn đọc", PannelQLBanDoc);

        jLabel21.setText("Nhà xuất bản");

        btnDatLaiTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiTaiLieu.setText("Đặt lại");

        jLabel22.setText("Giá");

        txtTimKiemTaiLieu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemTaiLieu.setText("Tìm kiếm");
        btnTimKiemTaiLieu.setNextFocusableComponent(txtMaTieuLieu);

        jLabel23.setText("Mã tài liệu");

        tblTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài liệu", "Tên tài liệu", "Số lượng", "Nhà xuất bản", "Giá"
            }
        ));
        jScrollPane4.setViewportView(tblTaiLieu);

        jLabel24.setText("Tên tài liệu");

        jLabel25.setText("Số lượng");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Quản lý Tài liệu");

        btnXemTatCaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaTaiLieu.setText("Xem tất cả");

        btnThemTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemTaiLieu.setText("Thêm");
        btnThemTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiLieuActionPerformed(evt);
            }
        });

        btnSuaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaTaiLieu.setText("Sửa");

        btnXoaTaiLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaTaiLieu.setText("Xóa");
        btnXoaTaiLieu.setName("Xóa"); // NOI18N

        javax.swing.GroupLayout PanelQLTaiLieuLayout = new javax.swing.GroupLayout(PanelQLTaiLieu);
        PanelQLTaiLieu.setLayout(PanelQLTaiLieuLayout);
        PanelQLTaiLieuLayout.setHorizontalGroup(
            PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel26)
                .addGap(0, 498, Short.MAX_VALUE))
            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaTieuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuongTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addComponent(txtTimKiemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiemTaiLieu))
                            .addComponent(btnSuaTaiLieu)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelQLTaiLieuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addComponent(btnDatLaiTaiLieu)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaTaiLieu))
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addComponent(btnXemTatCaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
        );

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatLaiTaiLieu, btnSuaTaiLieu, btnThemTaiLieu, btnXemTatCaTaiLieu, btnXoaTaiLieu});

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtGia, txtMaTieuLieu, txtNhaSanXuat, txtSoLuongTaiLieu, txtTenTaiLieu});

        PanelQLTaiLieuLayout.setVerticalGroup(
            PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemTaiLieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel24)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(PanelQLTaiLieuLayout.createSequentialGroup()
                                .addComponent(txtMaTieuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoLuongTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNhaSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaTaiLieu)
                            .addComponent(btnThemTaiLieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiTaiLieu)
                            .addComponent(btnXoaTaiLieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaTaiLieu))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDatLaiTaiLieu, btnSuaTaiLieu, btnThemTaiLieu, btnXemTatCaTaiLieu, btnXoaTaiLieu});

        PanelQLTaiLieuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtGia, txtMaTieuLieu, txtNhaSanXuat, txtSoLuongTaiLieu, txtTenTaiLieu});

        jTabbedPane2.addTab("Quản lý tài liệu", PanelQLTaiLieu);

        jLabel16.setText("Địa chỉ");

        btnDatLaiThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-synchronize-48.png"))); // NOI18N
        btnDatLaiThuThu.setText("Đặt lại");

        jLabel17.setText("Số điện thoại");

        btnDatLaiMatKhauThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-reset-48.png"))); // NOI18N
        btnDatLaiMatKhauThuThu.setText("Đặt lại mật khẩu");

        txtTimKiemThuThu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTimKiemThuThu.setText("Tìm kiếm");
        btnTimKiemThuThu.setNextFocusableComponent(txtMaThuThu);

        jLabel18.setText("Mã thủ thư");

        tblThuThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bạn đọc", "Tên bạn đọc", "Ngày sinh", "Địa chỉ", "Lớp"
            }
        ));
        jScrollPane3.setViewportView(tblThuThu);

        jLabel19.setText("Tên thủ thư");

        jLabel20.setText("Ngày sinh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Quản lý thủ thư");

        btnXemTatCaThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-select-all-48.png"))); // NOI18N
        btnXemTatCaThuThu.setText("Xem tất cả");

        btnThemThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-plus-48.png"))); // NOI18N
        btnThemThuThu.setText("Thêm");

        btnSuaThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-wrench-48.png"))); // NOI18N
        btnSuaThuThu.setText("Sửa");

        btnXoaThuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btnXoaThuThu.setText("Xóa");
        btnXoaThuThu.setName("Xóa"); // NOI18N

        javax.swing.GroupLayout PanelQLThuThuLayout = new javax.swing.GroupLayout(PanelQLThuThu);
        PanelQLThuThu.setLayout(PanelQLThuThuLayout);
        PanelQLThuThuLayout.setHorizontalGroup(
            PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addComponent(txtTimKiemThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiemThuThu))
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)))
                                .addGap(18, 18, 18)
                                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoDTThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenThuThu)
                                    .addComponent(dcNgaySinhThuThu, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtDiaChiThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXemTatCaThuThu)
                            .addComponent(btnDatLaiThuThu)
                            .addComponent(btnDatLaiMatKhauThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaThuThu)
                            .addComponent(btnSuaThuThu))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );

        PanelQLThuThuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcNgaySinhThuThu, txtDiaChiThuThu, txtMaThuThu, txtSoDTThuThu, txtTenThuThu});

        PanelQLThuThuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatLaiMatKhauThuThu, btnDatLaiThuThu, btnSuaThuThu, btnThemThuThu, btnXemTatCaThuThu, btnXoaThuThu});

        PanelQLThuThuLayout.setVerticalGroup(
            PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemThuThu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addComponent(txtMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelQLThuThuLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcNgaySinhThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(19, 19, 19)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChiThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDTThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemTatCaThuThu)
                            .addComponent(btnThemThuThu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiThuThu)
                            .addComponent(btnXoaThuThu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelQLThuThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatLaiMatKhauThuThu)
                            .addComponent(btnSuaThuThu)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        PanelQLThuThuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDatLaiMatKhauThuThu, btnDatLaiThuThu, btnSuaThuThu, btnThemThuThu, btnXemTatCaThuThu, btnXoaThuThu});

        jTabbedPane2.addTab("Quản lý thủ thư", PanelQLThuThu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemTaiLieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FrameAdmin().setVisible(true);
                }
            });
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrameAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelQLTaiLieu;
    private javax.swing.JPanel PanelQLThuThu;
    private javax.swing.JPanel PannelQLBanDoc;
    private javax.swing.JButton btnDatLaiBanDoc;
    private javax.swing.JButton btnDatLaiMatKhauBanDoc;
    private javax.swing.JButton btnDatLaiMatKhauThuThu;
    private javax.swing.JButton btnDatLaiTaiLieu;
    private javax.swing.JButton btnDatLaiThuThu;
    private javax.swing.JButton btnSuaBanDoc;
    private javax.swing.JButton btnSuaTaiLieu;
    private javax.swing.JButton btnSuaThuThu;
    private javax.swing.JButton btnThemBanDoc;
    private javax.swing.JButton btnThemTaiLieu;
    private javax.swing.JButton btnThemThuThu;
    private javax.swing.JButton btnTimKiemBanDoc;
    private javax.swing.JButton btnTimKiemTaiLieu;
    private javax.swing.JButton btnTimKiemThuThu;
    private javax.swing.JButton btnXemTatCaBanDoc;
    private javax.swing.JButton btnXemTatCaTaiLieu;
    private javax.swing.JButton btnXemTatCaThuThu;
    private javax.swing.JButton btnXoaBanDoc;
    private javax.swing.JButton btnXoaTaiLieu;
    private javax.swing.JButton btnXoaThuThu;
    private com.toedter.calendar.JDateChooser dcNgaySinhBanDoc;
    private com.toedter.calendar.JDateChooser dcNgaySinhThuThu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblBanDoc;
    private javax.swing.JTable tblTaiLieu;
    private javax.swing.JTable tblThuThu;
    private javax.swing.JTextField txtDiaChiBanDoc;
    private javax.swing.JTextField txtDiaChiThuThu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaBanDoc;
    private javax.swing.JTextField txtMaThuThu;
    private javax.swing.JTextField txtMaTieuLieu;
    private javax.swing.JTextField txtNhaSanXuat;
    private javax.swing.JTextField txtSoDTThuThu;
    private javax.swing.JTextField txtSoLuongTaiLieu;
    private javax.swing.JTextField txtTenBanDoc;
    private javax.swing.JTextField txtTenTaiLieu;
    private javax.swing.JTextField txtTenThuThu;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiemTaiLieu;
    private javax.swing.JTextField txtTimKiemThuThu;
    // End of variables declaration//GEN-END:variables
}
